name: 构建 Nextcloud Full-Apache

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:
    inputs:
      force_build:
        description: '是否覆盖已有同版本镜像（勾选后将强制构建并覆盖，默认为否）'
        required: false
        default: 'false'
        type: boolean

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/nextcloud-full-apache
  DOCKERFILE_PATH: ${{ github.workspace }}/.examples/dockerfiles/full/apache/Dockerfile
  # 若 Apache 版也需要 supervisord，可保留；否则删掉此 env，并移除相关检查步骤
  SUPERVISORD_CONF_PATH: ${{ github.workspace }}/.examples/dockerfiles/full/apache/supervisord.conf
  WORKING_DIR: .examples/dockerfiles/full/apache
  LAST_VERSION_FILE: .last_version_apache

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
    outputs:
      should_build: ${{ steps.decide.outputs.should_build }}
      latest_version: ${{ steps.decide.outputs.latest_version }}
    steps:
      - uses: actions/checkout@v4

      - name: 列出目录结构
        run: |
          echo "当前工作目录："
          pwd
          echo "仓库根目录内容："
          ls -la ${{ github.workspace }}
          echo "列出 ${{ env.WORKING_DIR }} 下的文件："
          ls -la || echo "目录不存在"

      - name: 检查文件是否存在
        run: |
          if [ -f "${{ env.DOCKERFILE_PATH }}" ]; then
            echo "Dockerfile 存在"
          else
            echo "Dockerfile 不存在：${{ env.DOCKERFILE_PATH }}"
            exit 1
          fi
          if [ -f "${{ env.SUPERVISORD_CONF_PATH }}" ]; then
            echo "supervisord.conf 存在"
          else
            echo "supervisord.conf 不存在：${{ env.SUPERVISORD_CONF_PATH }}"
            # 如果你 Apache 版不需要，就注释掉这一段检查即可
          fi

      - name: 展示 Dockerfile 前 10 行
        run: |
          head -n 10 "${{ env.DOCKERFILE_PATH }}" || true
          echo "-------------------------------------"

      - name: 展示 supervisord.conf 前 10 行
        run: |
          head -n 10 "${{ env.SUPERVISORD_CONF_PATH }}" || true
          echo "-------------------------------------"

      - name: 获取 Nextcloud 最新版本号
        id: upstream
        run: |
          set -e
          echo "尝试从 GitHub Releases 获取最新版本号..."
          GITHUB_RESPONSE=$(curl -fsSL "https://api.github.com/repos/nextcloud/server/releases/latest" || true)
          VERSION=$(echo "$GITHUB_RESPONSE" | jq -r '.tag_name' | sed 's/^v//')
          if [ -n "$VERSION" ] && [ "$VERSION" != "null" ]; then
            echo "从 GitHub Releases 获取到版本：$VERSION"
          else
            echo "GitHub Releases 未获取到版本，尝试 Docker Hub..."
            sudo apt-get update -y && sudo apt-get install -y jq
            TAGS_JSON=$(curl -fsSL "https://registry.hub.docker.com/v2/repositories/library/nextcloud/tags?page_size=100" || true)
            # 过滤掉 fpm / beta / rc，只保留 apache（默认）标签
            VERSION=$(echo "$TAGS_JSON" | jq -r '.results[].name' \
              | grep -E '^[0-9]+' \
              | grep -vE '(fpm|beta|rc)' \
              | sort -V | tail -n1)
            if [ -n "$VERSION" ]; then
              echo "从 Docker Hub 获取到版本：$VERSION"
            else
              echo "Docker Hub 未获取到版本，尝试镜像内查询..."
              docker pull nextcloud:apache
              VERSION=$(docker run --rm nextcloud:apache php -r 'require "/var/www/html/version.php"; echo implode(".", $OC_Version);')
              if [ -n "$VERSION" ]; then
                echo "从镜像中获取到版本：$VERSION"
              fi
            fi
          fi
          if [ -z "$VERSION" ]; then
            echo "无法获取 Nextcloud 版本号，终止构建"
            exit 1
          fi
          echo "latest_version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: 读取历史版本
        id: current
        run: |
          if [ -f "${{ github.workspace }}/${{ env.LAST_VERSION_FILE }}" ]; then
            echo "current_version=$(cat ${{ github.workspace }}/${{ env.LAST_VERSION_FILE }})" >> "$GITHUB_OUTPUT"
          else
            echo "current_version=none" >> "$GITHUB_OUTPUT"
          fi
        working-directory: ${{ github.workspace }}

      - name: 判断是否需要构建
        id: decide
        run: |
          FORCE_BUILD=${{ github.event.inputs.force_build || 'false' }}
          if [ "$FORCE_BUILD" == "true" ] || [ "${{ steps.upstream.outputs.latest_version }}" != "${{ steps.current.outputs.current_version }}" ]; then
            echo "将触发构建（强制构建: $FORCE_BUILD, 最新版本: ${{ steps.upstream.outputs.latest_version }}, 当前版本: ${{ steps.current.outputs.current_version }}）"
            echo "should_build=true" >> "$GITHUB_OUTPUT"
          else
            echo "无需构建（版本未变化）"
            echo "should_build=false" >> "$GITHUB_OUTPUT"
          fi
          echo "latest_version=${{ steps.upstream.outputs.latest_version }}" >> "$GITHUB_OUTPUT"

  build:
    needs: check
    if: needs.check.outputs.should_build == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: 登录到 GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 构建并推送镜像
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.WORKING_DIR }}
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ needs.check.outputs.latest_version }}
            ${{ env.IMAGE_NAME }}:latest
          build-args: |
            NEXTCLOUD_VERSION=${{ needs.check.outputs.latest_version }}

      - name: 更新版本记录
        run: echo "${{ needs.check.outputs.latest_version }}" > ${{ github.workspace }}/${{ env.LAST_VERSION_FILE }}

      - name: 提交版本变更
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: build Nextcloud Apache ${{ needs.check.outputs.latest_version }}"

      - name: 输出构建结果
        run: echo "已成功构建并推送 Nextcloud Full-Apache v${{ needs.check.outputs.latest_version }}"
